name: Run scratchattach script - scratch_chat.py

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Run on which OS?"
        type: choice
        required: true
        options:
          - "macos"
          - "ubuntu"
          - "windows"
        default: "ubuntu"
      pip:
        description: "Update pip?"
        type: boolean
        required: true
        default: true
  #schedule:
    #- cron: "* */6 * * *"

jobs:
  runranddb:
    name: 'Run Request/Database Handler'
    runs-on: "${{ github.events.inputs.runner == '' && 'ubuntu' || github.events.inputs.runner }}-latest"
    steps:
      - name: checkout repo content
        uses: actions/checkout@v6.0.1 # checkout the repository content to github runner
        with:
#          ref: v1.4.4a
          ref: scratch_chat_dev

      - name: setup python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: "3.14"
          check-latest: true
          
      - name: install dependencies
        run: pip install -r requirements.txt
        
      - name: recheckout repo content
        uses: actions/checkout@v6.0.1 # checkout the repository content to github runner
        with:
#          ref: v1.4.4a
          ref: scratch_chat_dev

      - name: execute scratch_chat.py
        env:
          PASS: ${{ secrets.SCRATCH_PASS }}
        run: |
          git config --global user.name 'Boss-1s [via Actions]'
          git config --global user.email 'Boss-1s[auto]@users.noreply.github.com'
          timeout 3m python3 scratch_chat.py || { [[ $? -eq 124 ]] && exit 0; }
        # timeout 358m 
          
      - name: push changes to scratch_chat_dev #main
        if: ${{ always() }}
        run: |
          bash push.sh
