name: Test key_multivalue_storage

on:
  push:
    paths:
      - 'key_multivalue_storage.py'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        py-ver: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.1
        with:
          ref: scratch_chat_dev
      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: ${{ matrix.py-ver }}
      - name: Run test file
        run: |
          cd test
          python3 o_test1.py
          
    
